name: "Regex validator"
description: "Validate a text against a regex pattern"
author: "Aleksander Fidelus"
branding:
  icon: "check-square"
  color: "black"

inputs:
  REGEX_PATTERN:
    required: true
    description: "Regex pattern to match the text against"
  TEXT:
    required: true
    description: "Text to evaluate"
  REGEX_MATCH_TYPE:
    required: false
    description: "Regex match type to use. One of [search, match, fullmatch]"
    default: "search"
outputs:
  MATCH:
    description: "true if TEXT matches the REGEX_PATTERN"
runs:
  using: "docker"
  image: "Dockerfile"
