name: Integration Test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          REGEX_PATTERN: test
          TEXT: ${{ github.event.pull_request.body }}
