name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'FidelusAleksander'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          #persist-credentials: false # TODO: change when using PAT for protected branches
          fetch-depth: 0
      - name: Release
        uses: cycjimmy/semantic-release-action@v3.4.2
        with:
          semantic_version: 19.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
