name: Release

on:
  push:
    branches:
      - master
      - semantic-release
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: cycjimmy/semantic-release-action@v3.4.2
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
